travis:
  secure:
    BINSTAR_TOKEN: Uw69jxE+sBW75teTsk+Li3mqTMp1p0pZAT1KZkbK12XcXpaCEGRCu2xAJE4+zgRWbqs/kDFQtXcn/2cyroAlNfErBDqtNyX+p7m6sVXgBImW8U63u02OXldIkadUn59fsfTg2HMMf6Xv0qn3V+F/hO1PVkKArdsEY03sPo5MHLKLVjWY2RaYQ8d1McyrKl0/QQue/DzJ/ZJ3YsjgqtpBHXjfwV0yy3viHg0SH/7VHgNzW1LDQ/Zmn8UUXaYwUykucMlITZN5VDkCMEA8PVaGNaeYtFNUzaK0qEJBw7KovaaKc1IcMPtzT9VFsOWVNjfiQB0w/UvaQsu5vSpX++tm6xj3TBplcjHqvydrctid4wEpw8+bDdfyzChcRY8DczGPnQJLOlCiabRVqYTqFlvlQd7sxYoGiCSTfJ8fpiOGwwmmunS+D5c7taXo3DtoxnQQ5bE47ngvty0KCjI86agJ2mkbn1MSb71OusYznixmlfXeIKxN7b+EmK3SyQRVXkF1a2i4FjgbIdE88JebWyf7CIP/n79J1+Q/yXgYkjC/Asgv6/f8eBk4vTY1hie4wBBMXBRzXlxDezKGMQXdJp6gyWcUuobZOn35wW2qU27QqyfLcAepBBTTddCd0j8m8dxLq52Pp2MyrYC9fiLOidI6MOjoeyjUrZek2yKCGuVPR7o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
