appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: MSG55l5yRVfolpvBLtnswk56kkap4DQXydAYeLydNQt2jHS0rCJWq7c72zGG4vZn2+ar+yAkPRsEm50HLMCPs4CF7xZ7FDP6j4lqAR/3KFYIzHg32ENVQQJ/OrgzDtBJzIwEqJz3cnEvXRTPn0XqlWvCvedeljQE16RvUn2fa1kqfLaJ9i88Js6lrND8Qg50Yu1Wm0E60dg5VZwylShV9MM1neBzv2cQJNgaNWmifgaH9H5uy0gIMTegpXyGrzEwt9g1EJxUdvCWhmIw1HUrfz7A1PwfpOyEitemztgtNXZuwaGSHb4bLd7NIfz6j0Hx7LCVJgICZkEZc4HC+43ddqJGlxF0ZPOyVW4FLViQ+VWBxg0uqsjHNghvsJ6lAoAUYN0x6RngQIDKW/tI/6U881ouQfKMisvwo+Up3wnYTIV9/d1iv2CqwGazHmeXAqsUyhAFjSLkCWciOA90ACmRng+v90PZptqAMQZK+JKnAO0bDIN2+yPlvrC7PJV8uVcH2/eJteuei+qAa7MroErmT9iVib7AlMicwkWorYrOxu2pipX6oA+evQs8klcqaDRHyqpefNb30tajmB/dl72QKWk9vkWGrGZZxL1ixGmpWsYEgjUfY44tjFvR3ODJK4i83a8RLaRoAiNuM8q0Fp8FT5GgIgWRlD4+ucO4y1GjX/M=}
conda_forge_output_validation: true
